from pathlib import Path


HELIX_URL = (
    "https://entelhelix.onbmc.com/arsys/forms/onbmc-s/"
    "SHR%3ALandingConsole/Default+Administrator+View/"
)
PROJECT_ROOT = Path(__file__).resolve().parents[1]
BROWSER_PROFILE_DIR = PROJECT_ROOT / "browser_profile"
LOG_DIR = PROJECT_ROOT / "logs"
SCREENSHOT_DIR = PROJECT_ROOT / "screenshots"

DEFAULT_TIMEOUT_MS = 60_000
NAVIGATION_TIMEOUT_MS = 90_000
SPA_READY_TIMEOUT_MS = 90_000
RESOLVER_FIELD_TIMEOUT_MS = 90_000
MENU_CLICK_TIMEOUT_MS = 30_000
CONSOLE_SETTLE_DELAY_MS = 2_000
MENU_SETTLE_DELAY_MS = 3_000
FIELD_SETTLE_DELAY_MS = 1_500
RESULT_SETTLE_DELAY_MS = 4_000
NETWORKS_TAB_SETTLE_DELAY_MS = 3_500
RESOLVER_GROUP_SETTLE_DELAY_MS = 2_500
RESOLVER_USER_SETTLE_DELAY_MS = 0
STATUS_MENU_SETTLE_DELAY_MS = 1_500
STATUS_SETTLE_DELAY_MS = 2_500
STATUS_REASON_MENU_SETTLE_DELAY_MS = 1_500
STATUS_REASON_SETTLE_DELAY_MS = 2_000
SAVE_TO_HOME_DELAY_MS = 3_000
SEARCH_ATTEMPTS = 2
